name: Run Random Thoughts API End-to-End Tests

on:
  workflow_call:
    inputs:
      runner:
        description: "The type of runner for this workflow (Default: ubuntu-latest)"
        required: false
        type: string
        default: ubuntu-latest
      app_name:
        description: "The name of the app under test by the e2e tests"
        required: false
        type: string
      app_image:
        description: "The app image under test by the e2e tests"
        required: false
        type: string
      e2e_tests_image:
        description: "Non-default End-to-End tests image to run"
        required: false
        type: string
      e2e_tests_command_prefix:
        description: "Command line prefix to add before e2e test command"
        required: false
        type: string
      workflow_ref:
        description: "The ref of the scripts used in the workflow"
        required: false
        type: string

jobs:
  e2e-tests:
    name: End-to-End Tests
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout e2e tests repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.workflow_ref }}
          repository: brianjbayer/random_thoughts_api_e2e

      - name: Run e2e tests
        run: |
          if [ -n "${{ inputs.app_name }}" ]; then
            app_msg="app: [${{ inputs.app_name }}] and image: [${{ inputs.app_image }}]"
            echo "Running e2e tests with ${app_msg}"
            APP_NAME=$(echo ${{ inputs.app_name }} | tr '[:lower:]' '[:upper:]')
            echo "APP_NAME: [${APP_NAME}]"

            # Must export, will not expand inline
            export "${APP_NAME}_IMAGE=${{ inputs.app_image }}"
          fi

          if [ -n "${{ inputs.e2e_tests_image }}" ]; then
            echo "Running e2e tests image: [${{ inputs.e2e_tests_image }}]"
            export E2ETESTS_IMAGE=${{ inputs.e2e_tests_image }}
            ${{ inputs.e2e_tests_command_prefix }} ./script/dockercomposerun -c
          else
            ${{ inputs.e2e_tests_command_prefix }} ./script/dockercomposerun
          fi
